# Generated by Django 4.0.3 on 2022-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=120)),
                ('courseId', models.IntegerField()),
                ('courseUId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=120)),
                ('studentRoll', models.IntegerField()),
                ('studentAge', models.IntegerField()),
                ('studentUID', models.IntegerField()),
            ],
        ),
    ]
